const UPDATE_VALUE = 'UPDATE_VALUE';
const PUT_DECIMAL = 'PUT_DECIMAL';
const CLEAR_VALUE = 'CLEAR_VALUE';
const REVERSE_SIGN = 'REVERSE_SIGN';
const REGISTER_ADD_OPERATION = 'REGISTER_ADD_OPERATION';
const REGISTER_SUBTRACT_OPERATION = 'REGISTER_SUBTRACT_OPERATION';
const REGISTER_MULTIPLY_OPERATION = 'REGISTER_MULTIPLY_OPERATION';
const REGISTER_DIVIDE_OPERATION = 'REGISTER_DIVIDE_OPERATION';
const SAVE_TO_PREVIOUS_VALUE = 'SAVE_TO_PREVIOUS_VALUE';
const EQUAL_OPERATION = 'EQUAL_OPERATION';

export {
  UPDATE_VALUE,
  PUT_DECIMAL,
  CLEAR_VALUE,
  REVERSE_SIGN,
  REGISTER_ADD_OPERATION,
  REGISTER_DIVIDE_OPERATION,
  REGISTER_MULTIPLY_OPERATION,
  REGISTER_SUBTRACT_OPERATION,
  SAVE_TO_PREVIOUS_VALUE,
  EQUAL_OPERATION,
};
